project:
  type: website

website:
  title: "Guides and Resources for Ocean Data Stewardship"
  page-navigation: true
  favicon: /img/Intertidal_Icon_Light_Color.png
  navbar: 
    title: false
    background: "#034969"
    logo: /img/Intertidal_PrimaryLogo_Bold_White.png
    logo-href: https://intertidal.agency/
    tools: 
      - icon: github
        href: https://github.com/intertidalagency/ia-guides-resources
      - icon: linkedin
        href: https://www.linkedin.com/company/intertidal-agency/
  search: 
    location: sidebar
    type: textbox
  sidebar:
    style: "floating"
    type: "light"
    background: "#034969"
    alignment: "left"
    border: false
    contents:
      - section: "Guides"
        contents: 
          - repository_review.qmd
          - defining_data_journey.qmd
      - text: "---"
      - section: "Resources"
        contents: 
          - repository_criteria.qmd
          - minimum_metadata.qmd
  page-footer: 
    center: "Content licensed CCBY 4.0, Intertidal Agency"
    background: "#0E7272"
        

format:
  html:
    theme:
      - default
      - custom.scss
    fontcolor: "#F3EDE4"
    linkcolor: "#30ACAE"
    backgroundcolor: "#034969"
    monobackgroundcolor: "#034969"
    toc: true
    page-layout: full
    grid:
      sidebar-width: 300px
      body-width: 2000px
      margin-width: 150px
      gutter-width: 3rem

editor: visual

