project:
  type: website
  output-dir: docs

website:
  title: "Guides and Resources for Ocean Data Stewardship"
  page-navigation: true
  favicon: /img/Intertidal_Icon_Bold_Color.png
  navbar: 
    title: false
    background: "#034969"
    logo: /img/Intertidal_PrimaryLogo_Bold_White.png
    logo-href: https://intertidal.agency/
  search: 
    location: sidebar
    type: textbox
  sidebar:
    style: "floating"
    type: "light"
    background: "#034969"
    alignment: "left"
    border: false
    contents:
      - section: "Guides"
        contents: 
          - repository_review.qmd
          - defining_data_journey.qmd
      - text: "---"
      - section: "Resources"
        contents: 
          - repository_criteria.qmd
          - minimum_metadata.qmd
  page-footer: 
    left: <img src="/img/Intertidal_PrimaryLogo_Bold_White.png" width="105">
    center: "Content licensed CCBY 4.0, Intertidal Agency"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/company/intertidal-agency/
      - icon: github
        href: https://github.com/intertidalagency/ia-guides-resources
    background: "#0E7272"

        

format:
  html:
    theme:
      - default
      - custom.scss
    fontcolor: "#ffffff"
    fontsize: 1.2rem
    # linkcolor: "#30ACAE"
    backgroundcolor: "#034969"
    # monobackgroundcolor: "#034969"
    toc: false
    author-meta: "Intertidal Agency"
    page-layout: full
    grid:
      sidebar-width: 300px
      body-width: 2000px
      margin-width: 150px
      gutter-width: 3rem

editor: visual

